

---
- name: Creating directories and files 
  hosts: all
  tasks:
   - name: Creating dir,files,changing permissions etc
     file:
      name: "{{item.a}}"
      state: "{{item.b}}"
      owner: "{{item.c}}"
      group: "{{item.d}}"
      mode: "{{item.e}}"
     with_items:
      - {a: mydir1,b: directory,c: sai,d: root,e: 777}
      - {a: mydir1/file1,b: touch,c: root,d: sai,e: 000}
      - {a: mydir1/dir2,b: directory,c: root,d: root,e: 765}
...
