---
- name: Installing apache2 
  hosts: 192.168.60.101
  tasks:
   - name: Installing apache2
     apt:
      name: apache2
      state: present
- name: Installing git
  hosts: 192.168.60.102
  tasks:
   - name: Installing git
     apt:
      name: git
      state: present
...

