

--- 
- name: Intalling apache2,starting it and checking url respo
  hosts: 192.168.60.101
  tasks:
   - name: Installing apache2
     apt:
      name: apache2
      state: present
      update_cache: yes
   - name: Startig apche2 service
     service:
      name: apache2
      state: started
   - name: Checking url response
     uri:
      url: http://192.168.60.101
      status: 200


...

