

---
- name: Installing packages 
  hosts: 192.168.60.101
  tasks:
   - name: Install packages
     apt:
      name: "{{item}}"
      state: present
      update_cache: yes
     with_items:
      - tree
      - git
      - maven
      - apache2
...
