

--- 
- name: For installig apache2,starting and checking url resp
  hosts: 192.168.60.101
  become: yes
  tasks:
   - name: Update apt repo and install apache2
     apt:
      name: apache2
      state: present
      update_cache : yes
   - name: Starting apache service
     service:
      name: apache2
      state: started
   - name: Checking url response
     uri:
      url: http://192.168.60.101
      status: 200


...
