


---
- name: For capturing user with /bin/bash shell
  hosts: all
  gather_facts: False
  tasks:
   - name: Capture info from /etc/passwd
     shell: grep /bin/bash /etc/passwd > file1
   - name: Fetching files
     fetch:
      src: /home/vagrant/file1
      dest: /home/vagrant



...
