

---
- name: Installing packages 
  hosts: 192.168.60.103
  tasks:
   - name: Installing pacakages
     apt:
      name: "{{item}}"
      state: present
      update_cache: yes
     with_items:
      - tree
      - git
      - maven      
...
