
---
- name: using handlers
  hosts: 192.168.60.101
  tasks:
   - name: copying content into index.html
     copy:
      content: "Sending data into index.html"
      dest: "/var/www/html/index.html"
     notify:
      - restart_apache2
  handlers:
   - name: restart_apache2
      service: 
      name: apache2
      state: restarted
